version: '3.8'

services:

  api:
    build: ./ms-cinema-api/
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:8000:8000

  loader:
    build: ./etl/
    env_file:
      - ./.env

  db:
    image: postgres:14.9-alpine3.18
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      - ./infra/postgres_init/movies_database.ddl:/docker-entrypoint-initdb.d/movies_db.sql
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./.env

  elastic:
    image: elasticsearch:8.6.2
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    depends_on:
      - db

  redis:
    image: redis:7.2.1-alpine
    #ports:
      #- "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data:rw

  nginx: 
    image: nginx:1.19.3 
    ports: 
      - 80:80
    expose:
      - 80
    restart: always 
    volumes: 
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/django_static/  
      - media_value:/var/html/django_media/ 

volumes:
  db_data:
  redis_data:
  elastic_data:
  static_value:
  media_value:
